-- YeranFood menu product architecture
-- Safe/idempotent migration. Never resets or deletes production orders.

create table if not exists public.menu_products (
  id bigint generated by default as identity primary key,
  menu_type text not null check (menu_type in ('breakfast','lunch')),
  name_zh text not null,
  name_en text,
  desc_zh text,
  desc_en text,
  price numeric(10,2) not null default 0 check (price >= 0),
  max_portions integer not null default 15 check (max_portions >= 0),
  active boolean not null default true,
  sort integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.product_options (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.menu_products(id) on delete cascade,
  label_zh text not null,
  label_en text,
  price numeric(10,2) not null default 0 check (price >= 0),
  max_portions integer not null default 15 check (max_portions >= 0),
  enabled boolean not null default true,
  sort integer not null default 0,
  desc_zh text,
  desc_en text,
  created_at timestamptz not null default now()
);

alter table public.orders add column if not exists product_id bigint;
alter table public.orders add column if not exists product_option_id bigint;

create index if not exists idx_orders_product on public.orders(product_id);
create index if not exists idx_orders_product_option on public.orders(product_option_id);
create index if not exists idx_menu_products_type on public.menu_products(menu_type);
create index if not exists idx_menu_products_active on public.menu_products(menu_type, active, sort);
create index if not exists idx_product_options_product on public.product_options(product_id);
create index if not exists idx_product_options_enabled on public.product_options(product_id, enabled, sort);

do $$
begin
  if not exists (select 1 from pg_constraint where conname='orders_product_id_fkey') then
    alter table public.orders add constraint orders_product_id_fkey
      foreign key (product_id) references public.menu_products(id) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname='orders_product_option_id_fkey') then
    alter table public.orders add constraint orders_product_option_id_fkey
      foreign key (product_option_id) references public.product_options(id) on delete set null;
  end if;
end $$;

alter table public.menu_products enable row level security;
alter table public.product_options enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='menu_products' and policyname='Public can view active menu products') then
    create policy "Public can view active menu products"
      on public.menu_products for select to anon, authenticated using (active = true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='product_options' and policyname='Public can view enabled product options') then
    create policy "Public can view enabled product options"
      on public.product_options for select to anon, authenticated using (enabled = true);
  end if;
end $$;

create or replace function public.get_product_stock(p_product_id bigint, p_meal_date date)
returns table(total integer, ordered integer, remaining integer)
language sql stable security definer
set search_path to 'public'
as $function$
  select
    mp.max_portions::integer,
    coalesce((select sum(o.quantity) from public.orders o
      where o.product_id=mp.id and o.meal_date=p_meal_date),0)::integer,
    greatest(0, mp.max_portions-coalesce((select sum(o.quantity)
      from public.orders o where o.product_id=mp.id and o.meal_date=p_meal_date),0))::integer
  from public.menu_products mp
  where mp.id=p_product_id and mp.active=true
  limit 1;
$function$;

create or replace function public.create_order_v2(
  p_request_id uuid,
  p_name text,
  p_quantity integer,
  p_note text,
  p_meal_date date,
  p_meal_period text,
  p_payment_method text,
  p_product_id bigint,
  p_option_id bigint default null
)
returns table(order_code text,total numeric,quantity integer,meal_type text,payment_status text)
language plpgsql security definer
set search_path to 'public'
as $function$
declare
  v_existing text;
  v_product public.menu_products%rowtype;
  v_option public.product_options%rowtype;
  v_ordered integer;
  v_code text;
  v_total numeric;
  v_meal_type text;
begin
  if p_request_id is null then raise exception 'INVALID_REQUEST'; end if;
  if length(trim(coalesce(p_name,''))) < 1 or length(trim(p_name)) > 80 then raise exception 'INVALID_NAME'; end if;
  if p_quantity is null or p_quantity < 1 or p_quantity > 50 then raise exception 'INVALID_QUANTITY'; end if;
  if p_meal_period not in ('lunch','breakfast') then raise exception 'INVALID_MEAL_PERIOD'; end if;
  if p_payment_method not in ('cash','online') then raise exception 'INVALID_PAYMENT_METHOD'; end if;
  if p_product_id is null then raise exception 'INVALID_PRODUCT'; end if;

  select r.order_code into v_existing
  from public.order_requests r where r.request_id=p_request_id;

  if v_existing is not null then
    return query
      select o.order_code,o.total,o.quantity,o.meal_type,coalesce(o.payment_status,'pending')
      from public.orders o where o.order_code=v_existing;
    return;
  end if;

  select mp.* into v_product
  from public.menu_products mp
  where mp.id=p_product_id and mp.menu_type=p_meal_period and mp.active=true
  for update;

  if not found then raise exception 'PRODUCT_UNAVAILABLE'; end if;

  if p_option_id is not null then
    select po.* into v_option
    from public.product_options po
    where po.id=p_option_id and po.product_id=v_product.id and po.enabled=true
    for update;
    if not found then raise exception 'OPTION_UNAVAILABLE'; end if;
    v_total := round(coalesce(v_option.price,0)*p_quantity,2);
    v_meal_type := coalesce(v_option.label_zh,v_option.label_en,v_product.name_zh,v_product.name_en,'—');
  else
    v_total := round(coalesce(v_product.price,0)*p_quantity,2);
    v_meal_type := coalesce(v_product.name_zh,v_product.name_en,'—');
  end if;

  select coalesce(sum(o.quantity),0) into v_ordered
  from public.orders o
  where o.meal_date=p_meal_date and o.product_id=v_product.id;

  if v_ordered+p_quantity > v_product.max_portions then raise exception 'OUT_OF_STOCK'; end if;

  v_code := 'YF-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,10));

  insert into public.orders(
    order_code,name,quantity,total,meal_type,note,payment_method,
    payment_proof,paid,meal_date,meal_period,payment_status,product_id,product_option_id
  )
  values(
    v_code,trim(p_name),p_quantity,v_total,v_meal_type,
    nullif(trim(coalesce(p_note,'')),''),p_payment_method,null,false,
    p_meal_date,p_meal_period,
    case when p_payment_method='online' then 'awaiting_proof' else 'pending' end,
    v_product.id,case when p_option_id is null then null else v_option.id end
  );

  insert into public.order_requests(request_id,order_code) values(p_request_id,v_code);

  return query
    select v_code,v_total,p_quantity,v_meal_type,
      case when p_payment_method='online' then 'awaiting_proof' else 'pending' end;
end;
$function$;